### ISSUE TITLE
A lot of invalid rows given current rules

### ISSUE THREAD

**Issue by akmiller01** [devinit/iati-budget-data#1]
Hi @bill-anderson, @dw8547 , I've got an application running now that validates rows of IATI data and prints them out to a CSV... Here's a small sample of the first 100ish. I've temporarily disabled the validity filter to debug the output, because only 1 row was counted as valid (row 25). Are we expecting such a high rate of filtered out rows?
[output_2016_11_07.xlsx](https://github.com/devinit/iati-budget-data/files/576065/output_2016_11_07.xlsx)

**Comment by akmiller01** [comment]
Also, does each row represent one budget within an activity? Or does one row represent one activity?

**Comment by akmiller01** [comment]
Alright. Code refactored to the budget level after our call @bill-anderson Again, this seems to exclude a lot of activities, but maybe AidData is all at the beginning? How does this output look to you so far? 
[output_2016_11_07.zip](https://github.com/devinit/iati-budget-data/files/576406/output_2016_11_07.zip)

**Comment by dw8547** [comment]
Hi @akmiller01, how does it look to me, @bill-anderson or @rory09?

**Comment by bill-anderson** [comment]
Leave it to me at this stage.

**Comment by bill-anderson** [comment]
That zip contained just one activity, right? (And one that I now propose ignoring as it has an invalid iati-identifier)

NB that the vast majority of activities don't contain budgets

cf.  http://dashboard.iatistandard.org/forwardlooking.html

Only 15,000 activities contain 2016 budgets

**Comment by akmiller01** [comment]
Okay. Are there any rules I should implement for ignoring invalid IATI
identifiers?

**Comment by bill-anderson** [comment]
https://github.com/devinit/iati-budget-data/issues/2
