### ISSUE TITLE
Exclude total value

### ISSUE THREAD

**Issue by bill-anderson** [devinit/iati-budget-data#6]
Not sure what this is?

**Comment by akmiller01** [comment]
`value = activity['aggregations']['activity']['budget_value']`

It's the total activity budget. Not useful?

**Comment by bill-anderson** [comment]
I don't think so

**Comment by akmiller01** [comment]
https://github.com/devinit/iati-budget-data/commit/a50c546dc4658cfdeecb7e298ffd9936fc7ccdfa
